# image: mhart/alpine-node:11
image: docker:git
services:
  - docker:dind

#VARIABLES GITLAB CI CD
#https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

stages: # List of stages for jobs, and their order of execution
  - build image Development

build-docker-img-dev:
  stage: build image Development
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - docker login registry.gitlab.com -u $USER -p $PASSWORD
    - docker build --pull -t $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA
    - docker images
  only:
    - desarrollo
