# image: mhart/alpine-node:11
image: docker:git
services:
  - docker:dind


stages:          # List of stages for jobs, and their order of execution
  - build

build-docker-img-prod:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker login registry.gitlab.com -u $USER -p $PASSWORD
    - docker build --pull -t $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG
    # - docker build -t test .
    - docker images
  only:
    - master

build-docker-img-dev:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install
    - npm run build
    - echo "Compile complete."
    - echo $REACT_APP_ENV
  only:
    - desarrollo

