image: docker:git
services:
  - docker:dind

#PREDEFINED VARIABLES GITLAB CI/CD
#https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
#NOTA: para que funcione el login las variables creadas en settings>CI/CD>variables de entorno no deben estar protected

stages: # List of stages for jobs, and their order of execution
  - Build
  - image Production
  - image Development

# COMPILE THE PROJECT
build-project:
  stage: Build
  image: mhart/alpine-node:11
  script:
    - echo REACT_APP_TEST
    - npm install
    - npm run build
    - cd build
    - ls
  artifacts:
    paths:
      - build/

# (MASTER)Build image and upload to registry
build-docker-img-prod:
  stage: image Production
  script:
    - echo ENVIROMENT $REACT_APP_ENV
    - docker login registry.gitlab.com -u $USER -p $PASSWORD
    - docker build --pull -t $CI_REGISTRY_IMAGE:prod-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:prod-$CI_COMMIT_SHORT_SHA
    - docker images
  only:
    - master

# (DEVELOP)Build image and upload to registry
build-docker-img-dev:
  stage: image Development
  script:
    - echo ENVIROMENT $REACT_APP_ENV
    - docker login registry.gitlab.com -u $USER -p $PASSWORD
    - docker build --pull -t $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA
    - docker images
  only:
    - desarrollo
